version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80
    depends_on:
      - php

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src/:/var/www/html/:delegated
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4-alpine3.14
    restart: always
    env_file:
      - ./envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 55432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -P postgres']
      interval: 2s
      timeout: 5s

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src/:/var/www/html/

  # artisan:
  # npm:

volumes:
  postgres_data: